services:
  - type: web
    name: flight-tickets-price-tracker-api
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    healthCheckPath: /health
    envVars:
      - key: SERPAPI_API_KEY
        sync: false
      - key: SERPAPI_API_KEY_2
        sync: false
      - key: SERPAPI_API_KEY_3
        sync: false
      - key: SERPAPI_API_KEY_4
        sync: false
      - key: SERPAPI_API_KEY_5
        sync: false
      - key: FLIGHT_API_ACCESS_TOKEN
        generateValue: true
